package io.snappify

object LanguageMap {
    private const val C = "c"
    private const val CPP = "cpp"
    private const val CSHARP = "csharp"
    private const val CLOJURE = "clojure"
    private const val COBOL = "cobol"
    private const val CSS = "css"
    private const val DART = "dart"
    private const val ELIXIR = "elixir"
    private const val ELM = "elm"
    private const val ERLANG = "erlang"
    private const val GHERKIN = "gherkin"
    private const val GRAPHQL = "graphql"
    private const val GROOVY = "groovy"
    private const val GO = "go"
    private const val HASKELL = "haskell"
    private const val HTML = "html"
    private const val JAVA = "java"
    private const val JAVASCRIPT = "javascript"
    private const val JSON = "json"
    private const val JSX = "jsx"
    private const val JULIA = "julia"
    private const val KOTLIN = "kotlin"
    private const val LUA = "lua"
    private const val NGINX = "nginx"
    private const val PASCAL = "pascal"
    private const val PERL = "perl"
    private const val PHP = "php"
    private const val POWERSHELL = "powershell"
    private const val PYTHON = "python"
    private const val R = "r"
    private const val RUBY = "ruby"
    private const val RUST = "rust"
    private const val SASS = "sass"
    private const val SCALA = "scala"
    private const val SMALLTALK = "smalltalk"
    private const val SQL = "sql"
    private const val STYLUS = "stylus"
    private const val SWIFT = "swift"
    private const val TOML = "toml"
    private const val TSX = "tsx"
    private const val TYPESCRIPT = "typescript"
    private const val VUE = "vue"
    private const val XML = "xml"
    private const val YAML = "yaml"

    private val mapping = mapOf(
            "_js" to JAVASCRIPT,
            "adml" to HTML,
            "admx" to XML,
            "al" to PERL,
            "ant" to XML,
            "app.src" to ERLANG,
            "avsc" to JSON,
            "aw" to PHP,
            "axml" to XML,
            "bones" to JAVASCRIPT,
            "boot" to CLOJURE,
            "builder" to RUBY,
            "builds" to XML,
            "c" to C,
            "c++" to CPP,
            "cake" to CSHARP,
            "cats" to C,
            "cbl" to COBOL,
            "cc" to CPP,
            "ccp" to COBOL,
            "ccproj" to XML,
            "ccxml" to XML,
            "cgi" to PERL,
            "cgi" to PYTHON,
            "cjs" to JAVASCRIPT,
            "cl2" to CLOJURE,
            "clixml" to XML,
            "clj" to CLOJURE,
            "cljc" to CLOJURE,
            "cljs" to CLOJURE,
            "cljs.hl" to CLOJURE,
            "cljscm" to CLOJURE,
            "cljx" to CLOJURE,
            "cob" to COBOL,
            "cobol" to COBOL,
            "cp" to CPP,
            "cpp" to CPP,
            "cproject" to XML,
            "cpy" to COBOL,
            "cql" to SQL,
            "cs" to CSHARP,
            "cs" to SMALLTALK,
            "cscfg" to XML,
            "csdef" to XML,
            "csl" to XML,
            "csproj" to XML,
            "css" to CSS,
            "csx" to CSHARP,
            "ct" to XML,
            "ctp" to PHP,
            "cxx" to CPP,
            "dart" to DART,
            "ddl" to SQL,
            "depproj" to XML,
            "dfm" to PASCAL,
            "dll.config" to XML,
            "dotsettings" to XML,
            "dpr" to PASCAL,
            "elm" to ELM,
            "erl" to ERLANG,
            "es" to ERLANG,
            "es" to JAVASCRIPT,
            "es6" to JAVASCRIPT,
            "escript" to ERLANG,
            "ex" to ELIXIR,
            "exs" to ELIXIR,
            "eye" to RUBY,
            "fcgi" to LUA,
            "fcgi" to PERL,
            "fcgi" to PHP,
            "fcgi" to PYTHON,
            "fcgi" to RUBY,
            "feature" to GHERKIN,
            "filters" to XML,
            "frag" to JAVASCRIPT,
            "fsproj" to XML,
            "fxml" to XML,
            "gemspec" to RUBY,
            "geojson" to JSON,
            "glade" to XML,
            "gltf" to JSON,
            "gml" to XML,
            "gmx" to XML,
            "go" to GO,
            "god" to RUBY,
            "gql" to GRAPHQL,
            "graphql" to GRAPHQL,
            "graphqls" to GRAPHQL,
            "groovy" to GROOVY,
            "grt" to GROOVY,
            "grxml" to XML,
            "gs" to JAVASCRIPT,
            "gtpl" to GROOVY,
            "gvy" to GROOVY,
            "gyp" to PYTHON,
            "gypi" to PYTHON,
            "h" to C,
            "h" to CPP,
            "h++" to CPP,
            "har" to JSON,
            "hh" to CPP,
            "hic" to CLOJURE,
            "hpp" to CPP,
            "hrl" to ERLANG,
            "hs" to HASKELL,
            "hs-boot" to HASKELL,
            "hsc" to HASKELL,
            "htm" to HTML,
            "html" to HTML,
            "html.hl" to HTML,
            "hxx" to CPP,
            "ice" to JSON,
            "idc" to C,
            "iml" to XML,
            "inc" to CPP,
            "inc" to XML,
            "inc" to PASCAL,
            "inc" to PHP,
            "inc" to SQL,
            "inl" to CPP,
            "ino" to CPP,
            "ipp" to CPP,
            "ivy" to XML,
            "jake" to JAVASCRIPT,
            "java" to JAVA,
            "jbuilder" to RUBY,
            "jelly" to XML,
            "jl" to JULIA,
            "js" to JAVASCRIPT,
            "jsb" to JAVASCRIPT,
            "jscad" to JAVASCRIPT,
            "jsfl" to JAVASCRIPT,
            "jsm" to JAVASCRIPT,
            "json" to JSON,
            "JSON-tmLanguage" to JSON,
            "jsonl" to JSON,
            "jsproj" to XML,
            "jss" to JAVASCRIPT,
            "jsx" to JSX,
            "kml" to XML,
            "kojo" to SCALA,
            "kt" to KOTLIN,
            "ktm" to KOTLIN,
            "kts" to KOTLIN,
            "launch" to XML,
            "linq" to CSHARP,
            "lmi" to PYTHON,
            "lpr" to PASCAL,
            "lua" to LUA,
            "map" to JSON,
            "mcmeta" to JSON,
            "mdpolicy" to XML,
            "mir" to YAML,
            "mjs" to JAVASCRIPT,
            "mm" to XML,
            "mod" to XML,
            "mspec" to RUBY,
            "mxml" to XML,
            "mysql" to SQL,
            "ndproj" to XML,
            "nginxconf" to NGINX,
            "njs" to JAVASCRIPT,
            "nproj" to XML,
            "nse" to LUA,
            "nuspec" to XML,
            "odd" to XML,
            "osm" to XML,
            "p8" to LUA,
            "pac" to JAVASCRIPT,
            "pas" to PASCAL,
            "pascal" to PASCAL,
            "pd_lua" to LUA,
            "perl" to PERL,
            "ph" to PERL,
            "php" to PHP,
            "php3" to PHP,
            "php4" to PHP,
            "php5" to PHP,
            "phps" to PHP,
            "phpt" to PHP,
            "pkgproj" to XML,
            "pl" to PERL,
            "pluginspec" to XML,
            "pluginspec" to RUBY,
            "plx" to PERL,
            "pm" to PERL,
            "podspec" to RUBY,
            "pp" to PASCAL,
            "prc" to SQL,
            "proj" to XML,
            "props" to XML,
            "ps1" to POWERSHELL,
            "ps1xml" to XML,
            "psc1" to XML,
            "psd1" to POWERSHELL,
            "psgi" to PERL,
            "psm1" to POWERSHELL,
            "pt" to XML,
            "py" to PYTHON,
            "py3" to PYTHON,
            "pyde" to PYTHON,
            "pyi" to PYTHON,
            "pyp" to PYTHON,
            "pyt" to PYTHON,
            "pyw" to PYTHON,
            "r" to R,
            "rabl" to RUBY,
            "rake" to RUBY,
            "rb" to RUBY,
            "rbi" to RUBY,
            "rbuild" to RUBY,
            "rbw" to RUBY,
            "rbx" to RUBY,
            "rbxs" to LUA,
            "rd" to R,
            "rdf" to XML,
            "re" to CPP,
            "reek" to YAML,
            "resx" to XML,
            "rockspec" to LUA,
            "rpy" to PYTHON,
            "rs" to RUST,
            "rs.in" to RUST,
            "rss" to XML,
            "rsx" to R,
            "ru" to RUBY,
            "ruby" to RUBY,
            "rviz" to YAML,
            "sass" to SASS,
            "sbt" to SCALA,
            "sc" to SCALA,
            "scala" to SCALA,
            "scxml" to XML,
            "sfproj" to XML,
            "shproj" to XML,
            "sjs" to JAVASCRIPT,
            "smk" to PYTHON,
            "spec" to PYTHON,
            "spec" to RUBY,
            "sql" to SQL,
            "srdf" to XML,
            "ssjs" to JAVASCRIPT,
            "st" to XML,
            "st" to SMALLTALK,
            "storyboard" to XML,
            "styl" to STYLUS,
            "sublime-snippet" to XML,
            "sublime-syntax" to YAML,
            "swift" to SWIFT,
            "syntax" to YAML,
            "t" to PERL,
            "tab" to SQL,
            "tac" to PYTHON,
            "targets" to XML,
            "tcc" to CPP,
            "tfstate" to JSON,
            "tfstate.backup" to JSON,
            "thor" to RUBY,
            "tml" to XML,
            "toml" to TOML,
            "topojson" to JSON,
            "tpp" to CPP,
            "ts" to TYPESCRIPT,
            "tsx" to TSX,
            "udf" to SQL,
            "vbproj" to XML,
            "vcxproj" to XML,
            "vhost" to NGINX,
            "viw" to SQL,
            "vsixmanifest" to XML,
            "vssettings" to XML,
            "vstemplate" to XML,
            "vue" to VUE,
            "vxml" to XML,
            "watchr" to RUBY,
            "webapp" to JSON,
            "webmanifest" to JSON,
            "wixproj" to XML,
            "wlua" to LUA,
            "workflow" to XML,
            "wsdl" to XML,
            "wsf" to XML,
            "wsgi" to PYTHON,
            "wxi" to XML,
            "wxl" to XML,
            "wxs" to XML,
            "x3d" to XML,
            "xacro" to XML,
            "xaml" to XML,
            "xht" to XML,
            "xhtml" to XML,
            "xib" to XML,
            "xlf" to XML,
            "xliff" to XML,
            "xmi" to XML,
            "xml" to XML,
            "xml.dist" to XML,
            "xproj" to XML,
            "xpy" to PYTHON,
            "xrl" to ERLANG,
            "xsd" to XML,
            "xsjs" to JAVASCRIPT,
            "xsjslib" to JAVASCRIPT,
            "xspec" to XML,
            "xul" to XML,
            "yaml" to YAML,
            "yaml-tmlanguage" to YAML,
            "yaml.sed" to YAML,
            "yml" to YAML,
            "yml.mysql" to YAML,
            "yrl" to ERLANG,
            "yy" to JSON,
            "yyp" to JSON,
            "zcml" to XML
    )

    fun forFileExtension(extension: String?): String {
        if (extension == null) {
            return JAVASCRIPT
        }
        return mapping[extension] ?: JAVASCRIPT
    }
}